# Generated by Django 4.1 on 2023-04-17 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категория аты')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тегі')),
                ('message', models.TextField(verbose_name='Хабарлама')),
            ],
            options={
                'verbose_name': 'Байланыс',
                'verbose_name_plural': 'Байланыстар',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тегі')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Қолданушы',
                'verbose_name_plural': 'Қолданушы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Өнім аты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Бағасы')),
                ('image', models.ImageField(upload_to='product_image/', verbose_name='Сурет')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Өнім',
                'verbose_name_plural': 'Өнімдер',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Сурет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Өнім')),
            ],
            options={
                'verbose_name': 'Сурет',
                'verbose_name_plural': 'Суреттер',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Саны')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
                ('status', models.BooleanField(default=False, verbose_name='Орындалды ма?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Қолданушы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Өнім')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыстар',
            },
        ),
    ]
