# Generated by Django 4.1 on 2023-04-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact_created_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=150, verbose_name='Қала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.IntegerField(default=1, verbose_name='Үй'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.IntegerField(default=1, verbose_name='Үй номері'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=1, max_length=150, verbose_name='Көше'),
            preserve_default=False,
        ),
    ]
