# Generated by Django 4.1 on 2023-04-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_order_city_order_house_order_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oplata',
            field=models.CharField(default=1, max_length=30, verbose_name='Төлем түрі'),
            preserve_default=False,
        ),
    ]
